In [708]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/gender_submission.csv
/kaggle/input/titanic/test.csv


In [709]:
data=pd.read_csv('/kaggle/input/titanic/train.csv')
test=pd.read_csv('/kaggle/input/titanic/test.csv')


In [710]:
test.shape

(418, 11)

In [711]:
data.set_index('PassengerId',inplace=True)

In [712]:
test.set_index('PassengerId',inplace=True)


In [713]:
test.shape

(418, 10)

In [714]:
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [715]:
data.isna().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [716]:
data.drop(['Cabin','Ticket','Name'],inplace=True,axis=1)

In [717]:
test.drop(['Cabin','Ticket','Name'],inplace=True,axis=1)

In [718]:
data.columns,test.columns

(Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
        'Embarked'],
       dtype='object'),
 Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object'))

In [719]:
data=pd.get_dummies(data)

In [720]:
data.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  \
PassengerId                                                              
1                   0       3  22.0      1      0   7.2500           0   
2                   1       1  38.0      1      0  71.2833           1   
3                   1       3  26.0      0      0   7.9250           1   
4                   1       1  35.0      1      0  53.1000           1   
5                   0       3  35.0      0      0   8.0500           0   

             Sex_male  Embarked_C  Embarked_Q  Embarked_S  
PassengerId                                                
1                   1           0           0           1  
2                   0           1           0           0  
3                   0           0           0           1  
4                   0           0           0           1  
5                   1           0           0           1

In [721]:
test=pd.get_dummies(test)

In [722]:
data.dropna(axis=0,how='any',inplace=True)

In [723]:
test.shape

(418, 10)

In [724]:
test['Age'].mean()

30.272590361445783

In [725]:
test['Age'].fillna(test['Age'].mean(),inplace=True)
test['Fare'].fillna(test['Fare'].mean(),inplace=True)

In [726]:
test['Age'].isna().sum()

0

In [727]:
test.drop('Age',axis=1)

Pclass  SibSp  Parch      Fare  Sex_female  Sex_male  Embarked_C  \
PassengerId                                                                     
892               3      0      0    7.8292           0         1           0   
893               3      1      0    7.0000           1         0           0   
894               2      0      0    9.6875           0         1           0   
895               3      0      0    8.6625           0         1           0   
896               3      1      1   12.2875           1         0           0   
...             ...    ...    ...       ...         ...       ...         ...   
1305              3      0      0    8.0500           0         1           0   
1306              1      0      0  108.9000           1         0           1   
1307              3      0      0    7.2500           0         1           0   
1308              3      0      0    8.0500           0         1           0   
1309              3      1      1   22.3583           0         1           1   

             Embarked_Q  Embarked_S  
PassengerId                          
892                   1           0  
893                   0           1  
894                   1           0  
895                   0           1  
896                   0           1  
...                 ...         ...  
1305                  0           1  
1306                  0           0  
1307                  0           1  
1308                  0           1  
1309                  0           0  

[418 rows x 9 columns]

In [728]:
data.isna().sum(),test.isna().sum()

(Survived      0
 Pclass        0
 Age           0
 SibSp         0
 Parch         0
 Fare          0
 Sex_female    0
 Sex_male      0
 Embarked_C    0
 Embarked_Q    0
 Embarked_S    0
 dtype: int64,
 Pclass        0
 Age           0
 SibSp         0
 Parch         0
 Fare          0
 Sex_female    0
 Sex_male      0
 Embarked_C    0
 Embarked_Q    0
 Embarked_S    0
 dtype: int64)

In [729]:
y=data['Survived']
X=data.drop(['Survived'],axis=1)
X.head()
X_test=test
X.head()

Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
PassengerId                                                              
1                 3  22.0      1      0   7.2500           0         1   
2                 1  38.0      1      0  71.2833           1         0   
3                 3  26.0      0      0   7.9250           1         0   
4                 1  35.0      1      0  53.1000           1         0   
5                 3  35.0      0      0   8.0500           0         1   

             Embarked_C  Embarked_Q  Embarked_S  
PassengerId                                      
1                     0           0           1  
2                     1           0           0  
3                     0           0           1  
4                     0           0           1  
5                     0           0           1

In [730]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=0)

In [731]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)
lrpred=lr.predict(X_val)
lrpred

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [732]:
accuracy_score(y_val,lrpred)

0.8391608391608392

In [733]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=0)

In [734]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [735]:
pred=rf.predict(X_val)

In [736]:
pred

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1])

In [737]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val,pred)

0.7692307692307693

In [738]:
lr_tpred=lr.predict(X_test)

In [739]:
lr_tpred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [740]:
submission = pd.DataFrame()

In [741]:
submission['PassengerId'] = X_test.index
submission['Survived'] = lr_tpred

In [742]:
submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [743]:
g=pd.read_csv('/kaggle/input/titanic/gender_submission.csv')
g.shape

(418, 2)

In [744]:
submission.to_csv('submission_titanic.csv', header=True, index=False)

In [745]:
submission.shape

(418, 2)